- name: Create  VM
  hosts: localhost
  connection: local
  tasks:
  - name: Remove VM One
    azure_rm_virtualmachine:
      name: table5dwvmone
      state: absent
      force: true
  - name: Remove VM Two
    azure_rm_virtualmachine:
      name: table5dwvmtwo
      state: absent
      force: true
