- hosts: localhost
  connection : local
  vars:
    group: table5dwwebapprg
    webapp_name: table5dwwebapp
    location: brazilsouth
  tasks:
    - name: Create Resource Group
      azure_rm_resourcegroup:
        name: "{{ group }}"
        location: "{{ location }}"
    - name: Create App Svc
      azure_rm_webapp:
        resource_group: "{{ group }}"
        name: "{{ webapp_name}}"
        plan:
          resource_group: "{{ group }}"
          name: table5dwappplan
          is_linux: true
          sku: S1
          number_of_workers: 1
        frameworks:
          - name: java
            version: "8"
            settings: 
              java_container: tomcat
              java_container_version: 8.5
